### ISSUE TITLE
uninitialized constant Filelock::Timeout

### ISSUE THREAD

**Issue by kylekyle** [sheerun/filelock#4]
Running the following example from the README:

```ruby 
require 'filelock'

Filelock '/tmp/path/to/lock', :wait => 3600 do
  # do blocking operation
end
```

results in the following stack trace:

```
/Users/kyle/.rvm/gems/ruby-2.2.1/gems/filelock-1.1.0/lib/filelock/exec_timeout.rb:2:in `<module:Filelock>': uninitialized constant Filelock::Timeout (NameError)
	from /Users/kyle/.rvm/gems/ruby-2.2.1/gems/filelock-1.1.0/lib/filelock/exec_timeout.rb:1:in `<top (required)>'
	from /Users/kyle/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kyle/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kyle/.rvm/gems/ruby-2.2.1/gems/filelock-1.1.0/lib/filelock.rb:2:in `<top (required)>'
	from /Users/kyle/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/kyle/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/kyle/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from lock.rb:1:in `<main>'
```

Moving the `require "timeout"` to the top of `firelock.rb` fixes the issue.

**Comment by kylekyle** [comment]
PR submitted for this.
